apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-playground
  namespace: dev
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wil-playground
  template:
    metadata:
      labels:
        app: wil-playground
    spec:
      containers:
      - name: wil-playground
        image: wil42/playground:v1
        ports:
        - containerPort: 8888

---
# Service: Expose l'application via un Service NodePort
apiVersion: v1
kind: Service
metadata:
  name: wil-playground-service
  namespace: dev
spec:
  type: NodePort  # Service de type NodePort pour exposer l'application à l'extérieur du cluster
  selector:
    app: wil-playground
  ports:
  - port: 8888  # Port sur lequel le service est exposé (le même que le containerPort)
    targetPort: 8888  # Port à l'intérieur du conteneur
    nodePort: 30001  # Le port sur lequel le service sera accessible en dehors du cluster (entre 30000 et 32767)
